DELIMITER ;;
DROP PROCEDURE IF EXISTS migrate;;
CREATE PROCEDURE migrate ()
BEGIN
    DECLARE CONTINUE HANDLER FOR 1060 BEGIN END;
    ALTER TABLE codereview_patchset ADD COLUMN revision VARCHAR (500);
END;;
CALL migrate();;
