DELIMITER ;;
DROP PROCEDURE IF EXISTS migrate;;
CREATE PROCEDURE migrate ()
BEGIN
    DECLARE CONTINUE HANDLER FOR 1060 BEGIN END;
    ALTER TABLE codereview_issue ADD COLUMN processing BOOLEAN;
END;;
CALL migrate();;
