DELIMITER ;;
DROP PROCEDURE IF EXISTS migrate;;
CREATE PROCEDURE migrate ()
BEGIN
    DECLARE CONTINUE HANDLER FOR 1060 BEGIN END;
    ALTER TABLE codereview_account ADD COLUMN fogbugz_token VARCHAR(255);
END;;
CALL migrate();;
